### ISSUE TITLE
禁用区分代码输入框的自动纠错/自动首字母大写/拼写自动校验

### ISSUE THREAD

**Issue by oe** [xlsdg/flower-password-hybrid-app#1]
在区分代码中输入英文字母时往往不是要输入英文单词，输入框默认的 **自动纠错** **自动首字母大写** **自动拼写校验** 非常影响输入，往往需要来回删除重新输入才能输入最终的文字。 HTML的input/textarea标签有一系列属性可以禁用这些行为 https://davidwalsh.name/disable-autocorrect 。Native语言也有相应的方法来禁用这些行为。

**Comment by xlsdg** [comment]
v1.0.21 版本已经修改，过阵子会发布到线上。
附花密（高级版）iOS版彩蛋：在联系作者界面，一直点击红色大头像。

**Comment by xlsdg** [comment]
v1.0.21 版本已经正式上线App Store和Google Play。

**Comment by oe** [comment]
Good job!

On June 16, 2016 at 10:07:03, xLsDg (notifications@github.commailto:notifications@github.com) wrote:

v1.0.21 版本已经正式上线App Store和Google Play。
